version: "1.0"
info:
  model: int-scaffold
packages:
- name: SampleFlowProject
  gitServerName: KritikasGitHubAccount
  gitUrl: https://github.com/KitNabber/SampleFlowProject
  gitUsername: KitNabber
  gitBranch: main
services:
- serviceName: project.sampleflow.integrations:SampleFlow
  packages:
  - name: SampleFlowProject
    version: "1.0"
- serviceName: pub.flow:getLastFailureCaught
  packages:
  - name: WmPublic
    version: 11.0.0.0.656
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.656
